"use client";

import React from "react";
import { X, Zap, AlertTriangle, AlertCircle, Info, Radio, Clock, ShieldCheck } from "lucide-react";
import { AIEvent } from "@/types/cyclone";
import { StatusBadge } from "../ui/StatusBadge";

interface AIEventsDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  events: AIEvent[];
  onSelectEventCyclone?: (cycloneId: string) => void;
}

export const AIEventsDrawer: React.FC<AIEventsDrawerProps> = ({
  isOpen,
  onClose,
  events,
  onSelectEventCyclone,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-black/50 backdrop-blur-[2px]">
      <div className="w-full max-w-md h-full bg-[#0B1120] border-l border-[#263449] flex flex-col shadow-2xl animate-in slide-in-from-right duration-200">
        {/* Header */}
        <div className="p-4 bg-[#111827] border-b border-[#263449] flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Zap className="w-4 h-4 text-[#F43F5E]" />
            <div>
              <h3 className="text-xs font-mono font-bold text-[#F8FAFC] tracking-wider uppercase">
                AI EVENTS & DETECTION STREAM
              </h3>
              <p className="text-[10px] text-[#94A3B8]">
                Real-time automated diagnostic triggers & rapid intensification flags
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-[#64748B] hover:text-[#F8FAFC] hover:bg-[#1E293B] rounded-[3px] transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Warning Disclaimer Notice */}
        <div className="p-2.5 bg-[#291B07] border-b border-[#5A3E11] text-[10px] font-mono text-[#F59E0B] flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 shrink-0" />
          <span>
            AUTOMATED AI DIAGNOSTICS: These events are generated by machine learning models and are not official government warnings.
          </span>
        </div>

        {/* Event List */}
        <div className="flex-1 overflow-y-auto p-3 space-y-3">
          {events.map((evt) => {
            return (
              <div
                key={evt.id}
                className="p-3 bg-[#111827] border border-[#263449] hover:border-[#334155] rounded-[4px] space-y-2 transition-colors"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-1.5">
                    <StatusBadge status={evt.severity} label={evt.severity} size="sm" />
                    <span className="text-xs font-mono font-bold text-[#F8FAFC]">
                      {evt.title}
                    </span>
                  </div>
                  <span className="text-[10px] font-mono text-[#94A3B8] shrink-0">
                    {evt.timestamp}
                  </span>
                </div>

                <div className="text-xs text-[#CBD5E1] leading-relaxed">
                  {evt.description}
                </div>

                {evt.supportingSignals && evt.supportingSignals.length > 0 && (
                  <div className="p-2 bg-[#070B14] border border-[#1E293B] rounded-[3px] space-y-1">
                    <span className="text-[10px] font-mono text-[#64748B] uppercase tracking-wider block">
                      SUPPORTING OBSERVATIONS:
                    </span>
                    <ul className="space-y-0.5 text-[11px] font-mono text-[#94A3B8]">
                      {evt.supportingSignals.map((signal, idx) => (
                        <li key={idx} className="flex items-start gap-1">
                          <span className="text-[#38BDF8]">•</span>
                          <span>{signal}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="flex items-center justify-between pt-1 border-t border-[#1E293B] text-[10px] font-mono">
                  <span className="text-[#64748B]">
                    TARGET: <span className="text-[#38BDF8]">{evt.cycloneName}</span>
                  </span>
                  {evt.confidencePercent && (
                    <span className="text-[#94A3B8]">
                      CONFIDENCE: <strong className="text-[#F8FAFC]">{evt.confidencePercent}%</strong>
                    </span>
                  )}
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer */}
        <div className="p-3 bg-[#0B1120] border-t border-[#263449] text-center">
          <span className="text-[10px] font-mono text-[#64748B]">
            All timestamps synchronized to UTC standard
          </span>
        </div>
      </div>
    </div>
  );
};
